group:
  # org-wide shared — synced to ALL repos
  - repos: |
      prathamudeshmukh/outbound-ui
      prathamudeshmukh/outbound-backend
      prathamudeshmukh/inbound-ui
      prathamudeshmukh/inbound-backend
    files:
      - source: .github/agents/
        dest: .github/agents/
      - source: .github/code-guidelines/
        dest: .github/code-guidelines/
      - source: .github/copilot-instructions.md
        dest: .github/copilot-instructions.md

  # squad-wide — outbound
  - repos: |
      prathamudeshmukh/outbound-ui
      prathamudeshmukh/outbound-backend
    files:
      - source: .github/squads/outbound/context/
        dest: .github/context/
      - source: .github/squads/outbound/stories/
        dest: .github/stories/

  # squad-wide — inbound
  - repos: |
      prathamudeshmukh/inbound-ui
      prathamudeshmukh/inbound-backend
    files:
      - source: .github/squads/inbound/context/
        dest: .github/context/
      - source: .github/squads/inbound/stories/
        dest: .github/stories/